# MySQL properties
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/securityandstrap?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=!n25nds&fsfXx
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.org.hibernate=DEBUG
#logging.level.org.springframework.web.servlet=DEBUG